language: python

sudo: false

matrix:
  include:
    - os: linux
      compiler: gcc
      addons: &gcc49
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9', 'gcc-4.9', 'gfortran-4.9']
      env:
        - CXX='g++-4.9'
        - CC='gcc-4.9'
        - FC='gfortran-4.9'
      python: 2.7
    - os: linux
      compiler: gcc
      addons: &gcc49
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9', 'gcc-4.9', 'gfortran-4.9']
      env:
        - CXX='g++-4.9'
        - CC='gcc-4.9'
        - FC='gfortran-4.9'
      python: 3.6
    - os: osx
      osx_image: xcode7.3
      compiler: gcc
      sudo: required
      language: generic

install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
        # manually install python on osx
        brew update &> /dev/null
        brew install python3
        brew reinstall gcc
        virtualenv venv
        source venv/bin/activate
        pip install -r requirements.txt --upgrade
    fi
  - pip install -r requirements.txt --upgrade
  - python --version

before_script:
  - pycodestyle account/
  - pycodestyle test/test.py

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test
  - cd ..
  - ACCOUNT_LIBRARY_DIR=$PWD/build/lib ACCOUNT_INCLUDE_DIR=$PWD/build/include PYTHONPATH=$PWD pytest -vv test/test.py

notifications:
  email: false
