sudo: false

dist: xenial

language: python

matrix:
  include:
    - os: linux
      python: 3.7
      addons:
        apt:
          packages: ['g++', 'gcc', 'gfortran']
      env:
        - CXX_COMPILER='g++'
        - C_COMPILER='gcc'
        - FC_COMPILER='gfortran'
    - os: osx
      addons:
        homebrew:
          packages:
            - gcc
            - cmake
      env:
        - CXX_COMPILER='g++'
        - C_COMPILER='gcc'
        - FC_COMPILER='gfortran'

before_install:
  - mkdir -p $HOME/Downloads $HOME/Deps

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      CMAKE_VERSION="3.14.7"
      echo "-- Installing CMake ${CMAKE_VERSION}"
      target_path=$HOME/Deps/cmake
      cmake_url="https://cmake.org/files/v${CMAKE_VERSION%.*}/cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz"
      mkdir -p "$target_path"
      curl -Ls "$cmake_url" | tar -xz -C "$target_path" --strip-components=1
      echo "-- Done with CMake ${CMAKE_VERSION}"
    fi
  - pip install --upgrade pip
  - pip install -U pipenv
  - pipenv install --dev 

before_script:
  - test -n $CXX && unset CXX
  - test -n $CC && unset CC
  - test -n $FC && unset FC
  - source $(pipenv --venv)/bin/activate

script:
  - export PATH=$HOME/Deps/cmake/bin${PATH:+:$PATH}
  - pycodestyle account/
  - pycodestyle test/test_account.py
  - >
      cmake -H. -Bbuild
        -DCMAKE_CXX_COMPILER=$CXX_COMPILER
        -DCMAKE_C_COMPILER=$C_COMPILER
        -DCMAKE_Fortran_COMPILER=$FC_COMPILER
        -DPython_ROOT_DIR=$(pipenv --venv)
  - cmake --build build -- VERBOSE=1
  - cd build
  - ctest
  - python -m pytest -rws -vv lib/python3.7
  - deactivate
  - cd ..
# in the remaining part test that we can pip install the code
  - mkdir test-setup-script
  - cd test-setup-script
  - virtualenv venv
  - source venv/bin/activate
  - pip install /home/travis/build/dev-cafe/context-api-example/
  - python -c 'import account'
  - deactivate

notifications:
  email: false
