sudo: false

dist: xenial

python: 3.7

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7', 'gcc-7', 'gfortran-7']
      env:
        - CXX_COMPILER='g++-7'
        - C_COMPILER='gcc-7'
        - FC_COMPILER='gfortran-7'
    - os: osx
      compiler: gcc
      addons:
        homebrew:
          packages:
            - gcc
            - cmake
      env:
        - CXX_COMPILER='g++'
        - C_COMPILER='gcc'
        - FC_COMPILER='gfortran'

before_install:
  - mkdir -p $HOME/Downloads $HOME/Deps

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      CMAKE_VERSION=3.14.7
      target_path=$HOME/Deps/cmake/$CMAKE_VERSION
      cmake_url="https://cmake.org/files/v${CMAKE_VERSION%.*}/cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz"
      mkdir -p "$target_path"
      curl -Ls "$cmake_url" | tar -xz -C "$target_path" --strip-components=1
      export PATH=$HOME/Deps/cmake/$CMAKE_VERSION/bin${PATH:+:$PATH}
    fi
  - pip install --upgrade pip
  - pip install -U pipenv
  - pipenv install --dev 

before_script:
  - test -n $CXX && unset CXX
  - test -n $CC && unset CC
  - test -n $FC && unset FC
  - source $(pipenv --venv)/bin/activate

script:
  - pycodestyle account/
  - pycodestyle test/test_account.py
  - cmake -H. -Bbuild -DCMAKE_CXX_COMPILER=$CXX_COMPILER -DCMAKE_C_COMPILER=$C_COMPILER -DCMAKE_Fortran_COMPILER=$FC_COMPILER
  - cmake --build build -- VERBOSE=1
  - cd build
  - ctest
  - python -m pytest -rws -vv lib/python3.7
  - cd ..
# in the remaining part test that we can pip install the code
  - mkdir test-setup-script
  - cd test-setup-script
  - virtualenv venv
  - source venv/bin/activate
  - pip install /home/travis/build/dev-cafe/context-api-example/
  - python -c 'import account'
  - deactivate

notifications:
  email: false
