sudo: false

dist: xenial

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7', 'gcc-7', 'gfortran-7']
      env:
        - CXX_COMPILER='g++-7'
        - C_COMPILER='gcc-7'
        - FC_COMPILER='gfortran-7'
    - os: osx
      compiler: gcc
      addons:
        homebrew:
          packages:
            - gcc
      env:
        - CXX_COMPILER='g++'
        - C_COMPILER='gcc'
        - FC_COMPILER='gfortran'

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create --name context-api-example python=3.7 pytest cffi pycodestyle cmake -c conda-forge

before_script:
  - test -n $CXX && unset CXX
  - test -n $CC && unset CC
  - test -n $FC && unset FC

script:
  - conda activate context-api-example
  - pycodestyle account/
  - pycodestyle test/test_account.py
  - cmake -H. -Bbuild -DCMAKE_CXX_COMPILER=$CXX_COMPILER -DCMAKE_C_COMPILER=$C_COMPILER -DCMAKE_Fortran_COMPILER=$FC_COMPILER
  - cmake --build build -- VERBOSE=1
  - cd build
  - ctest
  - python -m pytest -rws -vv lib/python3.7
  - cd ..
  - mkdir test-setup-script
  - cd test-setup-script
  - virtualenv venv
  - source venv/bin/activate
  - pip install git+https://github.com/bast/context-api-example.git
  - python -c 'import account'

notifications:
  email: false
